# security check
include:
  - project: "test-ci/gitlab-ci-template"
    ref: main
    file: "base-ci.yaml"

dev_build:
  stage: dev
  image: ubuntu:22.04
  extends: .build
  script:
    - source ansible-env/bin/activate
    - ansible --version