# security check
include:
  - project: "test-ci/gitlab-ci-template"
    ref: main
    file: "base-ci.yaml"

image_build_kaniko:
  stage: build
  extends: .docker_image_build_kaniko
  variables:
    DOCKERFILE: base.dockerfile
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"